// 翻译服务列表
export const translaterSerives = 
[
    "alibaba",
    "baidu",
    "bing",
    "deepl",
    "youdao",
    "qqtransmart",
    "sogou",
    "niutrans",
    "mymemory",
    "modernmt",
    "volcengine",
    "iciba",
    "iflytek",
    "google",
    "lingvanex",
    "yandex",
    "itranslate",
    "systran",
    "argos",
    "apertium",
    "reverso",
    "cloudtranslation",
    "translatecom",
    "tilde",
    "caiyun",
    "qqfanyi",
    "translateme",
    "papago",
    "mirai",
    "iflyrec",
    "hujiang",
    "yeekit",
    "languagewire",
    "elia",
    "judic",
    "mglip",
    "utibet"
]

export const language = 
[
    {"language": "chinese", "translator": "zh"},
    {"language": "english", "translator": "en"},
    {"language": "arabic", "translator": "ar"},
    {"language": "russian", "translator": "ru"},
    {"language": "french", "translator": "fr"},
    {"language": "german", "translator": "de"},
    {"language": "spanish", "translator": "es"},
    {"language": "portuguese", "translator": "pt"},
    {"language": "italian", "translator": "it"},
    {"language": "japanese", "translator": "ja"},
    {"language": "korean", "translator": "ko"},
    {"language": "greek", "translator": "el"},
    {"language": "dutch", "translator": "nl"},
    {"language": "hindi", "translator": "hi"},
    {"language": "turkish", "translator": "tr"},
    {"language": "malay", "translator": "ms"},
    {"language": "thai", "translator": "th"},
    {"language": "vietnamese", "translator": "vi"},
    {"language": "indonesian", "translator": "id"},
    {"language": "hebrew", "translator": "he"},
    {"language": "polish", "translator": "pl"},
    {"language": "mongolian", "translator": "mn"},
    {"language": "czech", "translator": "cs"},
    {"language": "hungarian", "translator": "hu"},
    {"language": "estonian", "translator": "et"},
    {"language": "bulgarian", "translator": "bg"},
    {"language": "danish", "translator": "da"},
    {"language": "finnish", "translator": "fi"},
    {"language": "romanian", "translator": "ro"},
    {"language": "swedish", "translator": "sv"},
    {"language": "slovenian", "translator": "sl"},
    {"language": "persian/farsi", "translator": "fa"},
    {"language": "bosnian", "translator": "bs"},
    {"language": "serbian", "translator": "sr"},
    {"language": "fijian", "translator": "fj"},
    {"language": "filipino", "translator": "tl"},
    {"language": "haitiancreole", "translator": "ht"},
    {"language": "catalan", "translator": "ca"},
    {"language": "croatian", "translator": "hr"},
    {"language": "latvian", "translator": "lv"},
    {"language": "lithuanian", "translator": "lt"},
    {"language": "urdu", "translator": "ur"},
    {"language": "ukrainian", "translator": "uk"},
    {"language": "welsh", "translator": "cy"},
    {"language": "tahiti", "translator": "ty"},
    {"language": "tongan", "translator": "to"},
    {"language": "swahili", "translator": "sw"},
    {"language": "samoan", "translator": "sm"},
    {"language": "slovak", "translator": "sk"},
    {"language": "afrikaans", "translator": "af"},
    {"language": "norwegian", "translator": "no"},
    {"language": "bengali", "translator": "bn"},
    {"language": "malagasy", "translator": "mg"},
    {"language": "maltese", "translator": "mt"},
    {"language": "queretaro otomi", "translator": "otq"},
    {"language": "klingon/tlhingan hol", "translator": "tlh"},
    {"language": "gujarati", "translator": "gu"},
    {"language": "tamil", "translator": "ta"},
    {"language": "telugu", "translator": "te"},
    {"language": "punjabi", "translator": "pa"},
    {"language": "amharic", "translator": "am"},
    {"language": "azerbaijani", "translator": "az"},
    {"language": "bashkir", "translator": "ba"},
    {"language": "belarusian", "translator": "be"},
    {"language": "cebuano", "translator": "ceb"},
    {"language": "chuvash", "translator": "cv"},
    {"language": "esperanto", "translator": "eo"},
    {"language": "basque", "translator": "eu"},
    {"language": "irish", "translator": "ga"}
]